import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#a4c9ff',
        'on-surface-variant': '#414751',
        'primary-container': '#005ea4',
        surface: '#fdf8f8',
        'tertiary-container': '#145da3',
        'inverse-on-surface': '#f4f0ef',
        'on-error': '#ffffff',
        'primary-fixed': '#d3e4ff',
        'on-tertiary-fixed': '#001c39',
        'on-tertiary-fixed-variant': '#004884',
        'on-error-container': '#93000a',
        background: '#fdf8f8',
        'secondary-fixed': '#9df4ce',
        'on-primary-fixed': '#001c38',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#bcd6ff',
        'deep-navy': '#0D1117',
        'on-background': '#1c1b1b',
        'on-primary-container': '#bbd7ff',
        'tertiary-fixed': '#d4e3ff',
        primary: '#00467c',
        'hairline-border': 'rgba(0, 0, 0, 0.08)',
        'inverse-primary': '#a1c9ff',
        tertiary: '#00457f',
        'surface-dim': '#ddd9d8',
        'on-surface': '#1c1b1b',
        'surface-bright': '#fdf8f8',
        'on-secondary-fixed': '#002115',
        'on-secondary-container': '#0b7052',
        'surface-variant': '#e6e1e1',
        'on-primary': '#ffffff',
        'surface-blue': '#E6F1FB',
        'primary-fixed-dim': '#a1c9ff',
        'surface-container-highest': '#e6e1e1',
        'surface-container-high': '#ece7e7',
        'surface-tint': '#0760a6',
        'secondary-fixed-dim': '#81d7b2',
        'surface-container-low': '#f7f2f2',
        'on-secondary-fixed-variant': '#00513a',
        'inverse-surface': '#313030',
        outline: '#717782',
        'surface-container': '#f1edec',
        secondary: '#006c4e',
        'on-secondary': '#ffffff',
        'secondary-container': '#9af1cb',
        error: '#ba1a1a',
        'outline-variant': '#c1c7d2',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004880',
        'warm-bg': '#F1EFE8',
        'neutral-gray': '#f8fafc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      spacing: {
        sm: '16px',
        md: '24px',
        gutter: '24px',
        base: '4px',
        margin: '32px',
        xl: '80px',
        lg: '48px',
        xs: '8px',
      },
      fontFamily: {
        caption: ['Plus Jakarta Sans'],
        'display-lg': ['Newsreader'],
        'headline-sm': ['Newsreader'],
        'body-md': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Newsreader'],
        'headline-md': ['Newsreader'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
        'body-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', fontWeight: '400' }],
        'headline-md': ['36px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.3', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
